CREATE DATABASE IF NOT EXISTS fithtech CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fithtech;

CREATE TABLE IF NOT EXISTS usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(120) NOT NULL,
 email VARCHAR(160) NOT NULL UNIQUE,
 telefone VARCHAR(30) NULL,
 senha_hash VARCHAR(255) NOT NULL,
 perfil ENUM('aluno','personal','admin') NOT NULL,
 bio VARCHAR(500) NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aluno_personal (
 id INT AUTO_INCREMENT PRIMARY KEY,
 aluno_id INT NOT NULL,
 personal_id INT NOT NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_aluno_personal (aluno_id,personal_id),
 CONSTRAINT fk_ap_aluno FOREIGN KEY (aluno_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 CONSTRAINT fk_ap_personal FOREIGN KEY (personal_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS treinos (
 id INT AUTO_INCREMENT PRIMARY KEY,
 aluno_id INT NOT NULL,
 personal_id INT NOT NULL,
 nome VARCHAR(120) NOT NULL,
 foco VARCHAR(180) NOT NULL,
 dias_semana TINYINT NOT NULL DEFAULT 3,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_treino_aluno FOREIGN KEY (aluno_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 CONSTRAINT fk_treino_personal FOREIGN KEY (personal_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS exercicios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 treino_id INT NOT NULL,
 nome VARCHAR(120) NOT NULL,
 grupo_muscular VARCHAR(80),
 series TINYINT,
 repeticoes VARCHAR(30),
 video_url VARCHAR(500),
 ordem TINYINT DEFAULT 1,
 CONSTRAINT fk_ex_treino FOREIGN KEY (treino_id) REFERENCES treinos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS progresso (
 id INT AUTO_INCREMENT PRIMARY KEY,
 aluno_id INT NOT NULL,
 exercicio_id INT NULL,
 exercicio_nome VARCHAR(120) NULL,
 treino_nome VARCHAR(120) NULL,
 concluido_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_prog_aluno FOREIGN KEY (aluno_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 CONSTRAINT fk_prog_ex FOREIGN KEY (exercicio_id) REFERENCES exercicios(id) ON DELETE SET NULL
);
